# === column rename mapping ===
column_mapping = {
    "index" : "NO",
    "name" : "hospital_name",
    "병원/약국명": "hospital_name",
    "병원/약국구분": "category",
    "소재지주소": "address",
    "전화번호": "phone",
    "우편번호": "postal_code",
    "홈페이지": "homepage_address",    
    "병상수": "num_beds",
    "의사수": "doctor_info",
    "진료과목내용": "specialties",    
    "특수진료가능분야": "special_fields",     
    "source_file": "source_file"       
}

department_mapping_snake_case = {
    "영상치의학과": "dental_radiology",
    "가정의학과": "family_medicine",
    "내과": "internal_medicine",
    "안과": "ophthalmology",
    "재활의학과": "rehabilitation_medicine",
    "한방내과": "oriental_internal",
    "신경외과": "neurosurgery",
    "치과": "dentistry",
    "방사선종양학과": "radiation_oncology",
    "핵의학과": "nuclear_medicine",
    "직업환경의학과": "occupational_medicine",
    "정신건강의학과": "psychiatry",
    "예방의학과": "preventive_medicine",
    "구강병리과": "oral_pathology",
    "치과보존과": "conservative_dentistry",
    "영상의학과": "radiology",
    "치과교정과": "orthodontics",
    "구강악안면외과": "oral_maxillofacial_surgery",
    "침구과": "acupuncture",
    "한방신경정신과": "oriental_neuropsychiatry",
    "응급의학과": "emergency_medicine",
    "통합치의학과": "integrated_dentistry",
    "한방부인과": "oriental_obgyn",
    "이비인후과": "ent",
    "병리과": "pathology",
    "치과보철과": "prosthodontics",
    "진단검사의학과": "lab_medicine",
    "비뇨의학과": "urology",
    "산부인과": "obstetrics_gynecology",
    "신경과": "neurology",
    "소아청소년과": "pediatrics",
    "구강내과": "oral_medicine",
    "치주과": "periodontology",
    "성형외과": "plastic_surgery",
    "피부과": "dermatology",
    "결핵과": "tuberculosis",
    "외과": "surgery",
    "소아치과": "pediatric_dentistry",
    "정형외과": "orthopedic_surgery",
    "마취통증의학과": "anesthesiology_pain",
    "심장혈관흉부외과": "cardiothoracic_surgery",
    "한방재활의학과": "oriental_rehab"
}

category_mapping = {
    "의원": "clinic",
    "약국": "pharmacy",
    "치과의원": "dental_clinic",
    "한의원": "oriental_clinic",
    "보건진료소": "public_health_center_branch",
    "병원": "hospital",
    "요양병원": "nursing_hospital",
    "보건지소": "public_health_subcenter",
    "한방병원": "oriental_hospital",
    "종합병원": "general_hospital",
    "정신병원": "psychiatric_hospital",
    "보건소": "public_health_center",
    "치과병원": "dental_hospital",
    "상급종합병원": "tertiary_hospital",
    "상급종합": "tertiary_hospital",
    "보건의료원": "public_medical_center",
    "조산원": "birth_center"
}

province_mapping = {
    "서울특별시": "Seoul",
    "부산광역시": "Busan",
    "대구광역시": "Daegu",
    "인천광역시": "Incheon",
    "광주광역시": "Gwangju",
    "대전광역시": "Daejeon",
    "울산광역시": "Ulsan",
    "세종특별자치시": "Sejong",
    "경기도": "Gyeonggi",
    "충청북도": "Chungbuk",
    "충청남도": "Chungnam",
    "전라북도": "Jeonbuk",
    "전라남도": "Jeonnam",
    "경상북도": "Gyeongbuk",
    "경상남도": "Gyeongnam",
    "제주특별자치도": "Jeju",
    "전북특별자치도": "Jeonbuk",
    "강원특별자치도": "Gangwon",
}